version: '2'
services:
  konewdb:
    restart: always
    build: ./konewdb

    command: [--auth]

    ports:
      - "37017:27017"
    volumes:
      - /home/tester/mongodb/konewdb/db:/data/db
      - /home/tester/mongodb/konewdb/configdb:/data/configdb
      - /home/tester/mongodb/backup:/data/backup
